"""initial_schema

Revision ID: 880e8eba07d0
Revises: 
Create Date: 2026-05-11 07:54:29.054334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '880e8eba07d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('daily_run_quota', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('github_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('github_username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('encrypted_token', sa.LargeBinary(), nullable=False),
    sa.Column('token_scopes', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_credentials_user_id'), 'github_credentials', ['user_id'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('github_owner', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('github_repo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('github_repo_id', sa.Integer(), nullable=True),
    sa.Column('default_branch', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('clone_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'github_owner', 'github_repo', name='uq_repo_user_owner_name')
    )
    op.create_index(op.f('ix_repositories_user_id'), 'repositories', ['user_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_usage_user_date')
    )
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    op.create_table('codebase_indexes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('indexed_commit_sha', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('chroma_collection_name', sqlmodel.sql.sqltypes.AutoString(length=63), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'indexing', 'ready', 'failed', name='index_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'branch', name='uq_codebase_index_repo_branch')
    )
    op.create_index(op.f('ix_codebase_indexes_repository_id'), 'codebase_indexes', ['repository_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('target_branch', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_repository_id'), 'tasks', ['repository_id'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='run_status'), nullable=False),
    sa.Column('parent_run_id', sa.UUID(), nullable=True),
    sa.Column('follow_up_instruction', sa.Text(), nullable=True),
    sa.Column('container_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('container_image', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('branch_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('max_turns', sa.Integer(), nullable=False),
    sa.Column('total_tool_calls', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_parent_run_id'), 'agent_runs', ['parent_run_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_task_id'), 'agent_runs', ['task_id'], unique=False)
    op.create_table('agent_run_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('status_change', 'plan', 'message', 'tool_call', 'tool_result', 'error', 'summary', name='event_type'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_run_events_run_seq', 'agent_run_events', ['agent_run_id', 'sequence'], unique=True)
    op.create_table('pull_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('github_pr_number', sa.Integer(), nullable=False),
    sa.Column('github_pr_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('head_branch', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('base_branch', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('state', sa.Enum('open', 'closed', 'merged', 'draft', name='pr_state'), nullable=False),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_run_id')
    )
    op.create_index(op.f('ix_pull_requests_repository_id'), 'pull_requests', ['repository_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tool_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'success', 'error', name='tool_call_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_agent_run_id'), 'tool_calls', ['agent_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_calls_agent_run_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_pull_requests_repository_id'), table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_index('ix_agent_run_events_run_seq', table_name='agent_run_events')
    op.drop_table('agent_run_events')
    op.drop_index(op.f('ix_agent_runs_task_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_parent_run_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_repository_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_codebase_indexes_repository_id'), table_name='codebase_indexes')
    op.drop_table('codebase_indexes')
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_repositories_user_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_github_credentials_user_id'), table_name='github_credentials')
    op.drop_table('github_credentials')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
