export const patchColors = {
  accent: "#0071e3",
  accentHover: "#0077ed",
  background: "#f5f5f7",
  border: "#e8e8ed",
  borderStrong: "#d2d2d7",
  chip: "rgba(210, 210, 215, 0.64)",
  chipHover: "#dcdce1",
  darkBorder: "#333333",
  ink: "#1d1d1f",
  muted: "#707070",
  onDarkMuted: "#d2d2d7",
  onDarkPanel: "rgba(255, 255, 255, 0.1)",
  surface: "#ffffff",
  surfaceTranslucent: "rgba(255, 255, 255, 0.7)",
  text: "#474747",
} as const;

export const patchCssVars = {
  accent: "var(--patch-accent)",
  accentHover: "var(--patch-accent-hover)",
  background: "var(--patch-bg)",
  border: "var(--patch-border)",
  borderStrong: "var(--patch-border-strong)",
  chip: "var(--patch-chip)",
  chipHover: "var(--patch-chip-hover)",
  darkBorder: "var(--patch-dark-border)",
  ink: "var(--patch-ink)",
  muted: "var(--patch-muted)",
  onDarkMuted: "var(--patch-on-dark-muted)",
  onDarkPanel: "var(--patch-on-dark-panel)",
  surface: "var(--patch-surface)",
  surfaceTranslucent: "var(--patch-surface-translucent)",
  text: "var(--patch-text)",
} as const;
